github: markec12345678
patreon: # Replace with Patreon username
open_collective: # Replace with Open Collective username
ko_fi: # Replace with Ko-fi username
tidelift: # Replace with Tidelift platform
community_bridge: # Replace with Community Bridge username
liberapay: # Replace with Liberapay username
issuehunt: # Replace with Issuehunt username
otechie: # Replace with Otechie username
lfx_crowdfunding: # Replace with LFX Crowdfunding username
custom: ['https://www.norolep-pos.si/donate']
