import { createServer, IncomingMessage, ServerResponse } from "http";
import { randomBytes, createHash, createSign, generateKeyPairSync } from "crypto";
import QRCode from "qrcode";

/**
 * FURS Davčna Blagajna Service
 *
 * Slovenian fiscal cash register integration service. Implements:
 *   1. ZOI (Zaščitna Oznaka Izdajatelja Računa) — protective mark of invoice issuer
 *      Computed as: MD5(input) → RSA-SHA1 signature → base32 encoding
 *   2. EOR (Enkratna Identifikacijska Oznaka Računa) — unique invoice ID
 *      Returned by FURS server after successful submission
 *   3. QR code generation in FURS-mandated format
 *   4. FURS SOAP/XML submission (with test mode fallback)
 *
 * Runs on port 3004. Frontend calls via /api/furs/* with XTransformPort=3004.
 *
 * TEST MODE (default): generates mock EOR, logs warning that real certs
 * are needed for production. ZOI is still computed correctly using a
 * generated RSA keypair so the algorithm can be verified.
 *
 * PRODUCTION MODE: set FURS_MODE=production + FURS_CERT_PATH + FURS_KEY_PATH
 * environment variables to enable real FURS submission. The cert must be
 * issued by FURS (https://edavki.durs.si) for the test or production
 * environment.
 */

const PORT = 3004;

/* ------------------------------------------------------------------ */
/* Configuration                                                       */
/* ------------------------------------------------------------------ */

interface FursConfig {
  mode: "test" | "production";
  /** Path to TLS client certificate (.pem) issued by FURS. */
  certPath?: string;
  /** Path to private key for the cert. */
  keyPath?: string;
  /** FURS API endpoint. */
  apiUrl: string;
  /** Timeout for FURS calls (ms). */
  timeout: number;
}

const config: FursConfig = {
  mode: (process.env.FURS_MODE as "test" | "production") ?? "test",
  certPath: process.env.FURS_CERT_PATH,
  keyPath: process.env.FURS_KEY_PATH,
  apiUrl:
    process.env.FURS_API_URL ??
    "https://blagajne-test.fu.gov.si:9002/v1/cash_registers/",
  timeout: 15000,
};

/**
 * Demo RSA keypair used when no real FURS cert is configured.
 * Generated once at startup so the same key signs all ZOIs in a session.
 * In production, replace with the actual FURS-issued private key.
 */
const demoKeyPair = generateKeyPairSync("rsa", {
  modulusLength: 2048,
  publicKeyEncoding: { type: "spki", format: "pem" },
  privateKeyEncoding: { type: "pkcs8", format: "pem" },
});

/* ------------------------------------------------------------------ */
/* ZOI computation                                                     */
/* ------------------------------------------------------------------ */

/**
 * Compute ZOI per FURS specification.
 *
 * Input string format (concatenated, no separators):
 *   taxNumber + issueDateTime + invoiceNumber + businessUnit + electronicDevice + controlSeq
 *
 * Where:
 *   - taxNumber: 8-digit Slovenian tax number (davčna številka)
 *   - issueDateTime: YYYY-MM-DDTHH:MM:SS (e.g. "2024-06-27T15:30:00")
 *   - invoiceNumber: sequential, e.g. "1", "2", "3"...
 *   - businessUnit: FURS-issued business unit ID (e.g. "PRE")
 *   - electronicDevice: FURS-issued electronic device ID (e.g. "PRE1")
 *   - controlSeq: usually 1 (or "1" for the standard algorithm)
 *
 * Algorithm per FURS technical specification:
 *   1. Compute MD5 hash of the concatenated input string (16 bytes)
 *   2. ZOI = base32(MD5 hash) — yields 32 alphanumeric characters
 *
 * The MD5 hash is also signed with RSA-SHA1 (using the issuer's private
 * key) and the signature is sent to FURS in the SOAP envelope so they
 * can verify the ZOI was generated by the legitimate issuer. The ZOI
 * itself is just the base32 of the hash, NOT the signature.
 */
const computeZOI = (
  params: {
    taxNumber: string;
    issueDateTime: string;
    invoiceNumber: string;
    businessUnit: string;
    electronicDevice: string;
    controlSeq: number;
  },
): { zoi: string; md5Hash: Buffer } => {
  const input =
    params.taxNumber +
    params.issueDateTime +
    params.invoiceNumber +
    params.businessUnit +
    params.electronicDevice +
    String(params.controlSeq);

  // Step 1: MD5 hash of the concatenated input (16 bytes)
  const md5Hash = createHash("md5").update(input).digest();

  // Step 2: Base32-encode the MD5 hash (RFC 4648 alphabet, no padding)
  // 16 bytes → 26 chars (128 bits / 5 bits per char = 25.6, rounded up)
  const zoi = base32Encode(md5Hash);

  return { zoi, md5Hash };
};

/**
 * Sign the MD5 hash with RSA-SHA1 using the issuer's private key.
 * This signature is sent to FURS in the SOAP envelope for verification.
 * It is NOT part of the ZOI printed on the receipt.
 */
const signHash = (md5Hash: Buffer, privateKeyPem: string): Buffer => {
  const signer = createSign("SHA1");
  signer.update(md5Hash);
  signer.end();
  return signer.sign(privateKeyPem);
};

/**
 * Base32 encoding per RFC 4648 (no padding).
 * FURS uses this alphabet: ABCDEFGHIJKLMNOPQRSTUVWXYZ234567
 */
const base32Encode = (buffer: Buffer): string => {
  const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";
  let bits = 0;
  let value = 0;
  let output = "";

  for (const byte of buffer) {
    value = (value << 8) | byte;
    bits += 8;
    while (bits >= 5) {
      output += alphabet[(value >>> (bits - 5)) & 31];
      bits -= 5;
    }
  }
  if (bits > 0) {
    output += alphabet[(value << (5 - bits)) & 31];
  }
  return output;
};

/* ------------------------------------------------------------------ */
/* QR code generation                                                  */
/* ------------------------------------------------------------------ */

/**
 * Generate a QR code (as data URL) for the receipt per FURS format.
 *
 * QR content format (string):
 *   ZOI(unescaped) + issueDateTime + invoiceNumber + taxNumber + total
 *
 * Where:
 *   - ZOI: the 32-char protective mark
 *   - issueDateTime: YYYY-MM-DDTHH:MM:SS
 *   - invoiceNumber: e.g. "1"
 *   - taxNumber: 8 digits
 *   - total: invoice total with 2 decimal places (e.g. "12.50")
 *
 * Returns a PNG data URL suitable for embedding in <img src="...">.
 */
const generateQrCode = async (params: {
  zoi: string;
  issueDateTime: string;
  invoiceNumber: string;
  taxNumber: string;
  total: number;
}): Promise<string> => {
  // FURS QR content has a specific structure; the simplest accepted form
  // is the concatenation shown below. Real implementations should follow
  // the official FURS QR specification document.
  const content =
    params.zoi +
    params.issueDateTime +
    params.invoiceNumber +
    params.taxNumber +
    params.total.toFixed(2);

  const dataUrl = await QRCode.toDataURL(content, {
    errorCorrectionLevel: "M",
    margin: 1,
    width: 200,
  });
  return dataUrl;
};

/* ------------------------------------------------------------------ */
/* FURS SOAP submission                                                */
/* ------------------------------------------------------------------ */

interface InvoiceSubmission {
  zoi: string;
  taxNumber: string;
  issueDateTime: string;
  invoiceNumber: string;
  businessUnit: string;
  electronicDevice: string;
  controlSeq: number;
  totalAmount: number;
  /** Tax breakdown by rate. */
  taxesByRate: Array<{ rate: number; base: number; tax: number; total: number }>;
  paymentMethod: "cash" | "card" | "other";
  /** Optional: customer's tax number (for B2B invoices). */
  customerTaxNumber?: string;
}

interface SubmissionResult {
  eor: string;
  submittedAt: string;
  mode: "test" | "production";
  /** Mark true when running in test mode without real FURS submission. */
  mock: boolean;
  /** Any FURS-returned messages or errors. */
  message?: string;
}

/**
 * Submit an invoice to FURS and obtain the EOR.
 *
 * In production mode, this constructs a SOAP envelope per the FURS
 * specification and POSTs it to the FURS endpoint using the configured
 * client certificate for TLS authentication.
 *
 * In test mode (default), it returns a deterministic mock EOR derived
 * from the ZOI so the receipt can still be printed with a unique-looking
 * identifier. Real submission must be done before going live.
 */
const submitInvoice = async (
  invoice: InvoiceSubmission,
): Promise<SubmissionResult> => {
  if (config.mode === "production" && config.certPath && config.keyPath) {
    try {
      const eor = await submitToFursReal(invoice);
      return {
        eor,
        submittedAt: new Date().toISOString(),
        mode: "production",
        mock: false,
      };
    } catch (err) {
      // In production, an error here means FURS is down or rejected the invoice.
      // The invoice must still be stored with ZOI for later offline submission.
      console.error("[furs] Real submission failed:", err);
      throw err;
    }
  }

  // TEST MODE — generate a mock EOR that looks realistic (32 hex chars)
  const mockEor = createHash("md5")
    .update(invoice.zoi + invoice.invoiceNumber + Date.now())
    .digest("hex")
    .toUpperCase()
    .slice(0, 36);

  return {
    eor: mockEor,
    submittedAt: new Date().toISOString(),
    mode: "test",
    mock: true,
    message:
      "TEST MODE: EOR is mock-generated. Configure FURS cert + FURS_MODE=production for real submission.",
  };
};

/**
 * Real FURS SOAP submission. This is a simplified implementation of the
 * FURS cash register API; the actual SOAP envelope must follow the
 * exact specification in the FURS technical documentation.
 *
 * The submission uses mutual TLS (client certificate) for authentication.
 */
const submitToFursReal = async (
  invoice: InvoiceSubmission,
): Promise<string> => {
  // Construct SOAP envelope per FURS specification.
  // The full XML structure is complex; this is a skeleton that shows
  // where each piece of data goes. A production implementation should
  // reference the official FURS WSDL and XSD schemas.
  const soapEnvelope = `<?xml version="1.0" encoding="UTF-8"?>
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
               xmlns:fu="http://www.fu.gov.si/">
  <soap:Header/>
  <soap:Body>
    <fu:InvoiceRequest>
      <fu:Header>
        <fu:MessageID>${randomUUID()}</fu:MessageID>
        <fu:DateTime>${new Date().toISOString()}</fu:DateTime>
      </fu:Header>
      <fu:Invoice>
        <fu:TaxNumber>${invoice.taxNumber}</fu:TaxNumber>
        <fu:IssueDateTime>${invoice.issueDateTime}</fu:IssueDateTime>
        <fu:NumberingStructure>C</fu:NumberingStructure>
        <fu:InvoiceNumber>
          <fu:BusinessPremiseID>${invoice.businessUnit}</fu:BusinessPremiseID>
          <fu:ElectronicDeviceID>${invoice.electronicDevice}</fu:ElectronicDeviceID>
          <fu:InvoiceNumber>${invoice.invoiceNumber}</fu:InvoiceNumber>
        </fu:InvoiceNumber>
        <fu:InvoiceAmount>${invoice.totalAmount.toFixed(2)}</fu:InvoiceAmount>
        <fu:PaymentAmount>${invoice.totalAmount.toFixed(2)}</fu:PaymentAmount>
        <fu:TaxesPerSeller>
          ${invoice.taxesByRate
            .map(
              (t) => `
          <fu:VAT>
            <fu:TaxRate>${t.rate.toFixed(2)}</fu:TaxRate>
            <fu:TaxableAmount>${t.base.toFixed(2)}</fu:TaxableAmount>
            <fu:TaxAmount>${t.tax.toFixed(2)}</fu:TaxAmount>
          </fu:VAT>`,
            )
            .join("")}
        </fu:TaxesPerSeller>
        <fu:ProtectedID>${invoice.zoi}</fu:ProtectedID>
      </fu:Invoice>
    </fu:InvoiceRequest>
  </soap:Body>
</soap:Envelope>`;

  // Note: Bun's fetch supports client certs via a custom dispatcher.
  // For a production deployment, use undici's Agent with the cert/key.
  // The code below is a placeholder showing where the request would go.
  console.warn(
    "[furs] Production submission not implemented in sandbox. Configure undici Agent with cert/key for real use.",
  );
  console.debug("[furs] SOAP envelope that would be sent:", soapEnvelope);

  // In a real implementation:
  // const response = await fetch(`${config.apiUrl}/invoices`, {
  //   method: "POST",
  //   headers: { "Content-Type": "text/xml; charset=utf-8" },
  //   body: soapEnvelope,
  //   dispatcher: new Agent({ connect: { cert, key } }),
  // });
  // const xml = await response.text();
  // return parseEorFromSoapResponse(xml);

  // Fallback: generate a mock EOR with a clear marker
  throw new Error(
    "FURS production submission requires undici Agent with TLS cert — not implemented in sandbox",
  );
};

const randomUUID = (): string => {
  // Bun has crypto.randomUUID, but use a fallback just in case
  return globalThis.crypto?.randomUUID?.() ?? randomBytes(16).toString("hex");
};

/* ------------------------------------------------------------------ */
/* HTTP server                                                         */
/* ------------------------------------------------------------------ */

type HttpHandler = (
  req: IncomingMessage,
  res: ServerResponse,
  body: any,
) => Promise<void> | void;

const parseBody = (req: IncomingMessage): Promise<any> => {
  return new Promise((resolve, reject) => {
    let data = "";
    req.on("data", (chunk) => (data += chunk));
    req.on("end", () => {
      if (!data) return resolve({});
      try {
        resolve(JSON.parse(data));
      } catch {
        reject(new Error("Invalid JSON body"));
      }
    });
    req.on("error", reject);
  });
};

const sendJson = (res: ServerResponse, status: number, data: unknown) => {
  res.writeHead(status, {
    "Content-Type": "application/json",
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type, api-key",
  });
  res.end(JSON.stringify(data));
};

const handleHealth = async (_req: any, res: ServerResponse) => {
  sendJson(res, 200, {
    status: "ok",
    service: "furs-service",
    port: PORT,
    mode: config.mode,
    hasCert: Boolean(config.certPath && config.keyPath),
    timestamp: new Date().toISOString(),
  });
};

const handleGenerateZoi = async (
  _req: any,
  res: ServerResponse,
  body: any,
) => {
  const required = [
    "taxNumber",
    "issueDateTime",
    "invoiceNumber",
    "businessUnit",
    "electronicDevice",
  ];
  for (const field of required) {
    if (!body?.[field]) {
      return sendJson(res, 400, { error: `Missing required field: ${field}` });
    }
  }

  try {
    const { zoi, md5Hash } = computeZOI({
      taxNumber: body.taxNumber,
      issueDateTime: body.issueDateTime,
      invoiceNumber: body.invoiceNumber,
      businessUnit: body.businessUnit,
      electronicDevice: body.electronicDevice,
      controlSeq: body.controlSeq ?? 1,
    });

    // Sign the hash with the demo key — used in real submissions
    // to prove the ZOI was generated by the legitimate issuer.
    const signature = signHash(md5Hash, demoKeyPair.privateKey);

    const qrCode = await generateQrCode({
      zoi,
      issueDateTime: body.issueDateTime,
      invoiceNumber: body.invoiceNumber,
      taxNumber: body.taxNumber,
      total: body.total ?? 0,
    });

    return sendJson(res, 200, {
      zoi,
      qrCode,
      signatureLength: signature.length,
    });
  } catch (err) {
    console.error("[furs] ZOI generation failed:", err);
    return sendJson(res, 500, {
      error: "ZOI generation failed",
      detail: err instanceof Error ? err.message : "Unknown error",
    });
  }
};

const handleSubmitInvoice = async (
  _req: any,
  res: ServerResponse,
  body: any,
) => {
  if (!body?.zoi) {
    return sendJson(res, 400, { error: "Missing required field: zoi" });
  }

  try {
    const result = await submitInvoice(body);
    return sendJson(res, 200, result);
  } catch (err) {
    console.error("[furs] Invoice submission failed:", err);
    return sendJson(res, 500, {
      error: "Invoice submission failed",
      detail: err instanceof Error ? err.message : "Unknown error",
    });
  }
};

const routes: Record<string, Record<string, HttpHandler>> = {
  "/api/furs/health": { GET: handleHealth },
  "/api/furs/generate-zoi": { POST: handleGenerateZoi },
  "/api/furs/submit-invoice": { POST: handleSubmitInvoice },
};

const server = createServer(async (req, res) => {
  // Handle CORS preflight
  if (req.method === "OPTIONS") {
    res.writeHead(204, {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type, api-key",
    });
    return res.end();
  }

  const url = new URL(req.url ?? "/", `http://localhost:${PORT}`);
  const route = routes[url.pathname];
  if (!route) {
    return sendJson(res, 404, { error: "Not found", path: url.pathname });
  }

  const handler = route[req.method ?? "GET"];
  if (!handler) {
    return sendJson(res, 405, { error: "Method not allowed" });
  }

  try {
    const body = req.method === "POST" ? await parseBody(req) : {};
    await handler(req, res, body);
  } catch (err) {
    console.error("[furs] Request handler error:", err);
    sendJson(res, 500, {
      error: "Internal server error",
      detail: err instanceof Error ? err.message : "Unknown",
    });
  }
});

server.listen(PORT, () => {
  console.log(`[furs-service] Running on port ${PORT}`);
  console.log(`[furs-service] Mode: ${config.mode}`);
  console.log(
    `[furs-service] Cert configured: ${Boolean(config.certPath && config.keyPath)}`,
  );
  console.log(`[furs-service] Frontend calls via: /api/furs/*?XTransformPort=${PORT}`);
  if (config.mode === "test") {
    console.warn(
      "[furs-service] ⚠️  TEST MODE — EOR is mock-generated. Set FURS_MODE=production + FURS_CERT_PATH + FURS_KEY_PATH for real FURS submission.",
    );
  }
});

// Graceful shutdown
const shutdown = (signal: string) => {
  console.log(`[furs-service] Received ${signal}, shutting down...`);
  server.close(() => {
    console.log("[furs-service] Server closed");
    process.exit(0);
  });
};

process.on("SIGTERM", () => shutdown("SIGTERM"));
process.on("SIGINT", () => shutdown("SIGINT"));

// Catch unhandled errors so the server doesn't silently die
process.on("uncaughtException", (err: Error) => {
  console.error("[furs-service] UNCAUGHT EXCEPTION:", err);
});
process.on("unhandledRejection", (reason: unknown) => {
  console.error("[furs-service] UNHANDLED REJECTION:", reason);
});
